name: Latest RadioGeek (YouTube)
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest Podcast from RadioGeek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "RadioGeek-YouTube"
          feed_list: "PL-tKrPVkKKE1peHomci9EH7BmafxdXKGn"
          max_post_count: 100