name: Latest RadioGeek (Google podcasts)
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-google-podcasts:
    name: Update this repo's README with latest Podcast from RadioGeek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "RadioGeek-GooglePodcasts"
          feed_list: "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy82MDQ4ODkwL3BvZGNhc3QvcnNz"
          max_post_count: 1000